# Generated by Django 5.2 on 2025-06-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='temp', max_length=50, unique=True)),
                ('name_ru', models.CharField(default='temp', max_length=50, null=True, unique=True)),
                ('name_en', models.CharField(default='temp', max_length=50, null=True, unique=True)),
                ('name_kk', models.CharField(default='temp', max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_catego_name_5111b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_kk', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('link', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='main_produc_slug_354b31_idx'), models.Index(fields=['name'], name='main_produc_name_168fc5_idx')],
            },
        ),
    ]
