# Generated by Django 5.2 on 2025-05-03 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='stars',
            field=models.PositiveIntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
