# Generated by Django 5.2 on 2025-05-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='slug',
            new_name='uni_slug',
        ),
    ]
