# Generated by Django 5.2 on 2025-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_slug_university_uni_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='uni_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='uni_name_kk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='uni_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
